数据的预处理需要根据数据本身的特性进行，有不同的格式要求，有缺失值的要填充，无用的数据要剔除。
数据的处理步骤：  
1）数据的准备  
2）数据的转换  
3）数据的输出  
本章节主要的部分：  
1）rescale data  
2) standardize data  
3) normalize data  
4) binarize data

# 1) scaler数据尺度的调整

In [22]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
filename ='/Users/wangjiabin/ML_2020_summer/<ml with python practice>/cha_7_data_visibility/pima_data.csv'
columns =['Pregnancies', 'Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']
dataset = read_csv(filename)
array = dataset.values
print(array.shape)
X =array[:,0:8]
Y=array[:,8]
'''通过此方式将数据进行范围上的缩放'''
transformer = MinMaxScaler(feature_range =(0,1))
newX = transformer.fit_transform(X)
set_printoptions(precision=3)
print(newX)

(768, 9)
[[0.353 0.744 0.59  ... 0.501 0.234 0.483]
 [0.059 0.427 0.541 ... 0.396 0.117 0.167]
 [0.471 0.92  0.525 ... 0.347 0.254 0.183]
 ...
 [0.294 0.608 0.59  ... 0.39  0.071 0.15 ]
 [0.059 0.633 0.492 ... 0.449 0.116 0.433]
 [0.059 0.467 0.574 ... 0.453 0.101 0.033]]


# 2)standardlize data 

In [31]:
from sklearn.preprocessing import StandardScaler
transformer = StandardScaler().fit(X)
newX = transformer.transform(X)
set_printoptions(precision = 3)
print(newX)

[[ 0.64   0.848  0.15  ...  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161 ... -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 ... -1.103  0.604 -0.106]
 ...
 [ 0.343  0.003  0.15  ... -0.735 -0.685 -0.276]
 [-0.845  0.16  -0.471 ... -0.24  -0.371  1.171]
 [-0.845 -0.873  0.046 ... -0.202 -0.474 -0.871]]


# 3)normalize data

In [36]:
from sklearn.preprocessing import Normalizer
transformer = Normalizer().fit(X)
newX = transformer.transform(X)
set_printoptions(precision =3)
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


# 4)binarize data

In [38]:
from sklearn.preprocessing import Binarizer
transformer = Binarizer(threshold =0.0).fit(X)
newX = transformer.transform(X)
set_printoptions(precision =3)
print(newX)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
