# 1. 数据预处理，分为6各部分。data preprocessing 

# step 1: import the required libraries

In [151]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
#from sklearn.impute import SimpleImputer

# step 2: importing dataset

In [152]:
'''此处编译花了一下午时间，尝试了绝对路径的r，以及/和\\等方法，后来才发现是文件名后面多添加了一个空格符,如下'''
dataset = pd.read_csv('/Users/wangjiabin/Desktop/summary/ML_preprocess/Data.csv')
X =dataset.iloc[:,:-1].values
print(X)
'iloc[:,:-1], :-1代表从右往左所有的值，但是不包含那列值，-1，代表那列值'
'country,age,salary,purchased'
Y= dataset.iloc[:,3].values
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# step 3: sloving missing data Nan

In [153]:
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
'''
numeric_features = ['Age','Salary']
numeric_transformer =Pipeline(steps=[('imputer',SimpleImputer(missing_values=np.nan,strategy='mean')),
                                     ('scaler',StandardScaler())])

categorical_features = ['Country','Purchased']
categorical_transformer = Pipeline(steps=[('imputer',SimpleImputer(strategy='contant',fill_value ='missing')),
                                          ('onehot',OneHotEncoder(handle_unknown='ignore'))])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])
numeric_transformer.fit()
X = dataset.drop('Purchased', axis=1)
y = dataset['Purchased']
print(X)
print(y)
'''
'pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest'


imputer =SimpleImputer(missing_values=np.nan, strategy='mean')
'Imputer实现对nan值的替换，可以替换成平均值，中位值等，axis=0代表列，1代表行，因为其应该有参考坐标'
imputer =imputer.fit(X[:,1:3])
'对X进行替换，用fit函数，之后再进行transform转换'
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)
print(Y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Step 4: 1) encoding categorical data

In [154]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X =LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
#X = onehotencoder.fit_transform(X).toarray()
#X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
print(X[:,0] )
print(Y)
#X=np.array(X)


[0 2 1 2 1 0 2 0 1 0]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# 2) creat dummy variable
#问题1：为什么用dummy：https://blog.csdn.net/u011467621/article/details/48754679
#问题2：onehotencoder 和 labelencoder， 两个不同的意义：https://zhuanlan.zhihu.com/p/33569866
#问题3：再解释https://medium.com/ai反斗城/preprocessing-data-onehotencoder-labelencoder-實作-968936124d59
# 此处https://www.cnblogs.com/zhoukui/p/9159909.html， 讨论fit()+transform() 和fit_transform()两种用法

In [155]:
from sklearn.compose import ColumnTransformer
#ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
#X = ct.fit_transform(X).toarray()
'''
# Country column
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])],     remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
'''
onehotencoder = OneHotEncoder(sparse = False)
X = onehotencoder.fit_transform(X)#.toarray()
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print(X)
print(Y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[0 1 0 0 1 1 0 1 0 1]


# step 5: spliting the datasets into training sets and test sets

In [156]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size =0.2, random_state =0)

# step 6: Feature scaling 

In [159]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train =sc_X.fit_transform(x_train)
x_test = sc_X.fit_transform(x_test)
print('x_train',x_train[0,:].shape)
print('y_train',y_train.shape)

x_train (23,)
y_train (8,)


In [160]:
'''import matplotlib.pyplot as plt 
x=np.arange(-4,4)
l1=plt.plot(x_train,y_train,'r--')
l2=plt.plot(x_test,y_test,'g--')
plt.scatter(x_train[0,:],y_train,'ro-',label='train')
plt.scatter(x_test,y_test,'g+-',label='test')
plt.title('train and test comparison')
plt.xlabel('row')
plt.ylabel('column')
plt.legend()
plt.show()'''

"import matplotlib.pyplot as plt \nx=np.arange(-4,4)\nl1=plt.plot(x_train,y_train,'r--')\nl2=plt.plot(x_test,y_test,'g--')\nplt.scatter(x_train[0,:],y_train,'ro-',label='train')\nplt.scatter(x_test,y_test,'g+-',label='test')\nplt.title('train and test comparison')\nplt.xlabel('row')\nplt.ylabel('column')\nplt.legend()\nplt.show()"

In [161]:
import sklearn
print(sklearn.__version__)

0.23.2


# Onehotencoder 解释：https://www.cnblogs.com/zhoukui/p/9159909.html

In [162]:
# -*- coding: utf-8 -*-

from sklearn.preprocessing import  OneHotEncoder

enc = OneHotEncoder()
enc.fit([[0, 0, 3],
         [1, 1, 0],
         [0, 2, 1],
         [1, 0, 2]])

ans = enc.transform([[0, 1, 3]]).toarray()  # 如果不加 toarray() 的话，输出的是稀疏的存储格式，即索引加值的形式，也可以通过参数指定 sparse = False 来达到同样的效果
print(ans) # 输出 [[ 1.  0.  0.  1.  0.  0.  0.  0.  1.]]

[[1. 0. 0. 1. 0. 0. 0. 0. 1.]]


In [163]:
[[1. 0. 1. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 1. 0. 0. 0. 0. 1.]]

SyntaxError: invalid syntax (<ipython-input-163-f6d0982906c7>, line 1)